export type Collection = 'lucide' | 'tabler' | 'phosphor'

export interface IconMeta {
  id: string
  name: string
  collection: Collection
  category: string
  tags: string[]
  /** Persian keywords (normalized), generated by the icon pipeline */
  f?: string
  /** path relative to public/icons/, e.g. "lucide/anchor.svg" */
  file: string
}

interface CollectionFile {
  collection: Collection
  icons: IconMeta[]
}

const cache = new Map<Collection, Promise<IconMeta[]>>()

const base = import.meta.env.BASE_URL

export function loadCollection(id: Collection): Promise<IconMeta[]> {
  let p = cache.get(id)
  if (!p) {
    p = fetch(`${base}icons/${id}/metadata.json`)
      .then((r) => {
        if (!r.ok) throw new Error(`Failed to load metadata for ${id}`)
        return r.json() as Promise<CollectionFile>
      })
      .then((d) => d.icons)
    cache.set(id, p)
  }
  return p
}

export function loadAllIcons(): Promise<IconMeta[]> {
  return Promise.all(COLLECTION_IDS.map(loadCollection)).then((lists) => lists.flat())
}

const COLLECTION_IDS: Collection[] = ['lucide', 'tabler', 'phosphor']
